const SMALLMOBILE = 365;
const MOBILLE = 480;
const SMALLTABLET = 768;
const LARGETABLET = 991;
const DESKTOP = 1366;

const MOBILE_MEDIA = 6;
const SMALL_TABLET_OR_LESS_MEDIA = 4;
const SMALL_TABLET_MEDIA = 3;
const TABLET_MEDIA = 2;
const TABLET_OR_LESS_MEDIA = 1;
const LARGE_TABLET_MEDIA = 5;
const DESKTOP_MEDIA = 0;
